### ISSUE TITLE
Suggestions 

### ISSUE THREAD

**Issue by nicolenam** [shehsarfraz/project-four-movie-gifs#16]
- It would be nice to add a "target= _blank" attribute to anchor tags in Display.js , so user does not navigate out of the website

` <a href={individualGifData.url}><img src={`https://media1.giphy.com/media/${individualGifData.id}/200.gif`} alt={individualGifData.title} /></a>`

**Comment by shehsarfraz** [comment]
Thank you, we will implement this!
